meta_nodes:
  Person:
    doc: >-
      Person data from University of Bristol.
    properties:
      name:
        doc: >-
          Name of person
        type: string
      url:
        doc: >-
          URL.
        type: string
      email:
        doc: >-
          Email.
        type: string
      orcid:
        doc: >-
          ORCID
        type: string
      job-description:
        doc: >-
          Job description
        type: string
      consent:
        doc: >-
          Consent to be included in search
        type: integer
    required:
      - name
      - url
      - email
      - consent
    index: email
    meta:
      _id: email
      _name: name  
  Org:
    doc: >-
      Organisation data.
    properties:
      name:
        doc: >-
          Name of organisation
        type: string
      type:
        doc: >-
          Type of organisation
        type: string
      id:
        doc: >-
          ID of organisation.
        type: string
    required:
      - name
      - type
      - id
    index: id
    meta:
      _id: id
      _name: name 
  Output:
    doc: >-
      Output data.
    properties:
      id:
        doc: >-
          ID of output.
        type: string
      title:
        doc: >-
          Title of output.
        type: string
      text:
        doc: >-
          Text of output.
        type: string
      year:
        doc: >-
          Year of output.
        type: integer
    required:
      - id
      - title
      - year
    index: id
    meta:
      _id: id
      _name: title 

meta_rels:
  PERSON_TO_ORG:
    doc: >-
      Connection between person and organisation
    properties:
      source:
        doc: ''
        type: Person
      target:
        doc: ''
        type: Org
    required:
      - source
      - target
  PERSON_TO_OUTPUT:
    doc: >-
      Connection between person and output
    properties:
      source:
        doc: ''
        type: Person
      target:
        doc: ''
        type: Output
    required:
      - source
      - target